Yksittäisen tuotteen tuotesivun rakentaminen AB#39
tapi2100/kukkakaupan-verkkosivut pull request #35
Opened 2024-03-29 07:24 UTC by Niqzu87

Uusi versio tuotesivusta.

2024-03-29 13:21 UTC, NiklasRosenberg commented
Hienosti tehty!

2024-03-29 13:21 UTC, NiklasRosenberg approved these changes

2024-03-29 13:22 UTC, NiklasRosenberg requested changes
Fonttikirjasto puuttuu.

2024-03-31 07:50 UTC, Niqzu87 commented
Lato fontti AB#46 mukaisesti lisätty

2024-03-31 09:33 UTC, tapi2100 approved these changes
Hyvältä näyttää. Jatkoon.

2024-03-31 11:09 UTC, merged